### ISSUE TITLE
return exception controller baru

### ISSUE THREAD

**Issue by ronincumi** [SymfonyId/Skeleton#2]
skeleton mempunya sistem dimana controller dibuat berdasarkan entity yg ada, jadi pada dasarnya memberikan kemudahan dev dalam melakukan crud, just siab:generate, and its done. 

yg menjadi masalah adalah ketika  ingin menambahkan controller baru dengan route, baik di class maupun method, SIAB tidak dapat mengenali route tersebut. jika di debug:route maka yg terjadi :

`Fatal error: Call to a member function isSubclassOf() on null in C:\xampp\htdocs\skeleton\vendor\symfonyid\admin-bundle\Route\SiabRouteLoader.php on line 62`

**Comment by ad3n** [comment]
@ronincumi : Coba update dependecies gan. Ane cek ga ada soalnya

Ketika menggunakan controller Route atau method Route tidak ada masalah

**Comment by ronincumi** [comment]
composer update --prefer-dist, dah beberape kali ane fresh install, bahkan tanpa generate siab, tapi hasilnya sama, setiap kali  buat controller baru buat route via annotation, tetep g dianggap kecuali extend CRUDcontroller, please check https://github.com/ronincumi/MySkeleton (belum digenerate)

**Comment by ad3n** [comment]
@ronincumi : saya coba di local route terdeteksi om

![screenshot from 2016-02-22 13 48 08](https://cloud.githubusercontent.com/assets/7464920/13212001/380da106-d970-11e5-86af-ef1520f22e0a.png)
