### ISSUE TITLE
Redis, optional atau wajib?

### ISSUE THREAD

**Issue by bangbambang** [SymfonyId/Skeleton#4]
Config bawaan menggunakan redis [sebagai session store](https://github.com/SymfonyId/Skeleton/blob/57fe39cbc15d89fbeaa1f4d981c397ecb8922fc3/app/config/config.yml#L29). Sementara di readme tidak disebutkan.
Yang harus diperbaiki README-nya atau confignya kah?

**Comment by ad3n** [comment]
Wajib gan

**Comment by ad3n** [comment]
Readme update ada di AdminBundle gan... Sorry
